#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define WINDOW_TITLE "Lol"

#define WINDOW_DEFAULT_WIDTH 640
#define WINDOW_DEFAULT_HEIGHT 480

#define DEFAULT_MAP_HEIGHT 100
#define DEFAULT_MAP_WIDTH 100

#define DEFAULT_WINDOWS_TILE 16

#endif // CONSTANTS_HPP
