#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define WINDOW_TITLE "Feed the supreme leader"
#define GAME_NAME "Feed the supreme leader"

#define WINDOW_DEFAULT_WIDTH 800
#define WINDOW_DEFAULT_HEIGHT 600

#define MAP_BORDER_WIDTH_MOVE 20
#define MAP_MOVE_SENSIVITY 6

#define DEFAULT_MAP_HEIGHT 100
#define DEFAULT_MAP_WIDTH 100
#define DEFAULT_MAP_MARGIN 10

#define DEFAULT_WINDOWS_TILE 16

#define GAME_INTERFACE_MENU_HEIGHT 192

#define COLOR_RED 0x8c1515ff
#define COLOR_LIGHT_RED 0xb01515ff
#define COLOR_YELLOW 0xc4be1dff
#define COLOR_LIGHT_YELLOW 0xede623ff


#endif // CONSTANTS_HPP
