#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define WINDOW_TITLE "Feed the supreme leader"
#define GAME_NAME "Feed the supreme leader"

#define WINDOW_DEFAULT_WIDTH 800
#define WINDOW_DEFAULT_HEIGHT 600

#define MAP_BORDER_WIDTH_MOVE 20
#define MAP_MOVE_SENSIVITY 6
#define WIDTH_DEAD_RATIO 0.2f
#define HEIGHT_DEAD_RATIO 0.1f

#define DEFAULT_MAP_HEIGHT 100
#define DEFAULT_MAP_WIDTH 100
#define DEFAULT_MAP_MARGIN 5

#define DEFAULT_WINDOWS_TILE 24

#define GAME_INTERFACE_MENU_HEIGHT 192
#define GAME_INTERFACE_MAP_WIDTH 192
#define GAME_INTERFACE_BUILDING_MENU_WIDTH 256

#define COLOR_RED 0x8c1515ff
#define COLOR_LIGHT_RED 0xb01515ff
#define COLOR_YELLOW 0xc4be1dff
#define COLOR_LIGHT_YELLOW 0xede623ff

#define COLOR_GREEN_MAP 0x1eb800ff
#define COLOR_FARM_MINIMAP 0x8f552dff
#define COLOR_HOUSE_MINIMAP 0x006fd9ff

#define MENU_DEF_BUTTON 0
#define MENU_LRG_BUTTON 1
#define MENU_BCKGRD     2
#define DEFAULT_TILE    3
#define ENTITY_FARM     4
#define BTN_MENU_GAME   5
#define BTN_MENU_GAME_CANCEL 6
#define FRAME_PAUSE_DURATION 30

#define CONFIG_FILE_NAME "config.json"

#define FARM_NAME "Farm"
#define HOUSE_NAME "House"
#define SCHOOL_NAME "School"

#endif // CONSTANTS_HPP
